name: myapp
description: "A new Flutter project."
publish_to: 'none' 

ersion: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  go_router: ^14.1.3 
  flutter_spinkit: ^5.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/fb.png
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/main_top.png
    - assets/images/signup_top.png
    - assets/images/tren22.png